In [ ]:
# -> combine multiple models
# -> to improve overall performance of ML models
# Goal -> enhance predictive accuracy

# Weak Learner WL -> Base Learner
# -> is learning algorithm capable of producing classifiers with probability of error
# -> stictly less than random guessing (binary classifiction -> 0.5)
# -> performs lesser than random guessing

# Strong Learner SL 
# -> yield classifiers with small error probaility
# -> perform better than random guessing

# Categories in Ensemble Learning
# 1. Sequential Ensemble Technique
# 2. Paralled Ensemble Technique

# 1. Sequential Ensemble Technique
# -> train models sequentially with each model attempting to correct its predecessor score
# -> Model1 -> Model2 (correct errors of Model1) -> Model3 -> 
# -> refining predictions sequentially
# -> Boosting - e.g. 

# The steps involved in the sequential ensemble technique depend on the data structure and the requirements of the application. They are:
# Base Model Selection: Choose the initial model.
# Sequential Training: Train models one after the other.
# Error Correction: Each model learns from previous mistakes.
# Prediction Refinement: Iteratively refine predictions.
# Combining Predictions: Combine predictions from all models.
# Evaluation: Assess ensemble performance using metrics.

# 2. Paralled Ensemble Technique
# The steps involved in the parallel ensemble technique are:
# 1.Data Partitioning: Divide the dataset into subsets
# 2.Model Training: Train models concurrently on subsets
# 3.Prediction: Models make independent predictions
# 4.Combining Predictions: Aggregate predictions using techniques like voting or averaging
# 5.Evaluation: Assess ensemble performance using metrics

# Voting technique
# -> involves the aggreagting the predictions from multiple models to arrive at a final prediction
# 1. Majority Voting (Hard Voting)
# -> every model makes its own prediction
# -> whichever prediction has a majority vote -> that is considered as final prediction

# 2. Weighted Voting (Soft Voting)
# -> takes the estimates from each model
# -> every model will give the probaility of each class - model 1 - class 0 class1 class2
# -> average out all these probabilities
# -> final prediction : class with highest average probability is considered

In [35]:
# Implement using Majority Voting Technique
import pandas as pd
# Load the dataset from the specified URL and assign column names to the DataFrame
data = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data', header=None)
data.columns = ['Sample code', 'Clump Thickness', 'Uniformity of Cell Size', 'Uniformity of Cell Shape',
                'Marginal Adhesion', 'Single Epithelial Cell Size', 'Bare Nuclei', 'Bland Chromatin',
                'Normal Nucleoli', 'Mitoses', 'Class']

In [37]:
data.head(10)

,Sample code,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses,Class
0,1000025,5,1,1,1,2,1,3,1,1,2
1,1002945,5,4,4,5,7,10,3,2,1,2
2,1015425,3,1,1,1,2,2,3,1,1,2
3,1016277,6,8,8,1,3,4,3,7,1,2
4,1017023,4,1,1,3,2,1,3,1,1,2
5,1017122,8,10,10,8,7,10,9,7,1,4
6,1018099,1,1,1,1,2,10,3,1,1,2
7,1018561,2,1,2,1,2,1,3,1,1,2
8,1033078,2,1,1,1,2,1,1,1,5,2
9,1033078,4,2,1,1,2,1,2,1,1,2

In [39]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Sample code                  699 non-null    int64
 1   Clump Thickness              699 non-null    int64
 2   Uniformity of Cell Size      699 non-null    int64
 3   Uniformity of Cell Shape     699 non-null    int64
 4   Marginal Adhesion            699 non-null    int64
 5   Single Epithelial Cell Size  699 non-null    int64
 6   Bare Nuclei                  699 non-null    object
 7   Bland Chromatin              699 non-null    int64
 8   Normal Nucleoli              699 non-null    int64
 9   Mitoses                      699 non-null    int64
 10  Class                        699 non-null    int64
dtypes: int64(10), object(1)
memory usage: 60.2+ KB

In [41]:
# drop sample code col
data.drop(['Sample code'], axis=1, inplace=True)

In [43]:
# convert bare nuclei to interger type
import numpy as np
data = data.replace('?',np.nan)
data['Bare Nuclei'] = pd.to_numeric(data['Bare Nuclei']).fillna(0).astype('int64')

In [45]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Clump Thickness              699 non-null    int64
 1   Uniformity of Cell Size      699 non-null    int64
 2   Uniformity of Cell Shape     699 non-null    int64
 3   Marginal Adhesion            699 non-null    int64
 4   Single Epithelial Cell Size  699 non-null    int64
 5   Bare Nuclei                  699 non-null    int64
 6   Bland Chromatin              699 non-null    int64
 7   Normal Nucleoli              699 non-null    int64
 8   Mitoses                      699 non-null    int64
 9   Class                        699 non-null    int64
dtypes: int64(10)
memory usage: 54.7 KB

In [47]:
# import libraries
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import VotingClassifier
from sklearn.impute import SimpleImputer

In [49]:
data.head(10)

,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses,Class
0,5,1,1,1,2,1,3,1,1,2
1,5,4,4,5,7,10,3,2,1,2
2,3,1,1,1,2,2,3,1,1,2
3,6,8,8,1,3,4,3,7,1,2
4,4,1,1,3,2,1,3,1,1,2
5,8,10,10,8,7,10,9,7,1,4
6,1,1,1,1,2,10,3,1,1,2
7,2,1,2,1,2,1,3,1,1,2
8,2,1,1,1,2,1,1,1,5,2
9,4,2,1,1,2,1,2,1,1,2

In [53]:
# Replace class values to binary ( 2 for benign, 4 for malignant)
data['Class'] = data['Class'].replace({2:0, 4:1})
data.head(10)

,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses,Class
0,5,1,1,1,2,1,3,1,1,0
1,5,4,4,5,7,10,3,2,1,0
2,3,1,1,1,2,2,3,1,1,0
3,6,8,8,1,3,4,3,7,1,0
4,4,1,1,3,2,1,3,1,1,0
5,8,10,10,8,7,10,9,7,1,1
6,1,1,1,1,2,10,3,1,1,0
7,2,1,2,1,2,1,3,1,1,0
8,2,1,1,1,2,1,1,1,5,0
9,4,2,1,1,2,1,2,1,1,0

In [55]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Clump Thickness              699 non-null    int64
 1   Uniformity of Cell Size      699 non-null    int64
 2   Uniformity of Cell Shape     699 non-null    int64
 3   Marginal Adhesion            699 non-null    int64
 4   Single Epithelial Cell Size  699 non-null    int64
 5   Bare Nuclei                  699 non-null    int64
 6   Bland Chromatin              699 non-null    int64
 7   Normal Nucleoli              699 non-null    int64
 8   Mitoses                      699 non-null    int64
 9   Class                        699 non-null    int64
dtypes: int64(10)
memory usage: 54.7 KB

In [57]:
# Extract features X and target y
X = data.iloc[:,:-1] # all cols except last
y = data.iloc[:,-1] # last col as target

# Perform train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [61]:
# scaling 
# MinMaxScaler -> scaling technique -> normalize the data
# -> transform features to specific range [0,1]
# -> cases where model is distance based
# -> For each feature x -> x_scaled = (x-xmin)/(xmax-xmin) * (max_range - min_range) + min_range
# x-> oroginal value
# xmin, xmax -> min and mix values of that feature in the dataset
# min_range, max_range -> desired scaling range -> default -> (0 to 1)

scaler = MinMaxScaler(feature_range=(0,1))
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [63]:
# multiple alogorithms -> LR,DTC,SVM

# initilaize these base estimators/models
estimators = [
    ('lr', LogisticRegression()),
    ('dtc', DecisionTreeClassifier()),
    ('svm',SVC())
]

In [71]:
from sklearn.model_selection import KFold, cross_val_score
# Create hard voting tehcnique
ensemble = VotingClassifier(estimators, voting = "hard")
# Setup KFold cross validation
# -> model validation technique -> assess how well a model generalizes to unseen data
Kfold = KFold(n_splits = 10, shuffle=True, random_state=42)
# n_splits -> number of folds
# -> 10 -> data will be splitted into 10 parts -> each part is called fold
# 1st time -> 1-9 for training, 10th for validation
# 2nd time -> 1-10 for training except 9th, 9th for validation
# -> model will train 10 times each time using 9 folds for training and 1 for vaidation
# shuffle = True
# -> randomly shuffle the data before splitting into folds
# -> order biased -> prevented
# Evalaute ensemble model
results = cross_val_score(ensemble, X_train_scaled, y_train, cv=Kfold)
print(f"Mean cross validation accuracy of ensemble model : {results.mean():.2f}")
# Fit the ensemble on scaled trainig set and test it for testing set
ensemble.fit(X_train_scaled, y_train)
test_accuracy = ensemble.score(X_test_scaled, y_test)
print(f"Test Accuracy of ensemble model : {test_accuracy:.2f}")

Mean cross validation accuracy of ensemble model : 0.96
Test Accuracy of ensemble model : 0.97

In [73]:
# predictions on testing set
# evaluate prediction - confusion matrix, classification report
y_pred = ensemble.predict(X_test_scaled)
print('Classification Report : ')
print(classification_report(y_test, y_pred))
print('Confusion Matrix : ')
print(confusion_matrix(y_test, y_pred))

Classification Report :
              precision    recall  f1-score   support

           0       0.98      0.98      0.98        95
           1       0.96      0.96      0.96        45

    accuracy                           0.97       140
   macro avg       0.97      0.97      0.97       140
weighted avg       0.97      0.97      0.97       140

Confusion Matrix :
[[93  2]
 [ 2 43]]

In [75]:
# reapeat same process with voting = soft
# make comparison - soft voting
# screenshots 

estimators = [
    ('lr', LogisticRegression()),
    ('dtc', DecisionTreeClassifier()),
    ('svm', SVC(probability=True))
]

In [77]:
from sklearn.model_selection import KFold, cross_val_score
ensemble = VotingClassifier(estimators, voting = "soft")
Kfold = KFold(n_splits = 10, shuffle=True, random_state=42)
results = cross_val_score(ensemble, X_train_scaled, y_train, cv=Kfold)
print(f"Mean cross validation accuracy of ensemble model : {results.mean():.2f}")
ensemble.fit(X_train_scaled, y_train)
test_accuracy = ensemble.score(X_test_scaled, y_test)
print(f"Test Accuracy of ensemble model : {test_accuracy:.2f}")

Mean cross validation accuracy of ensemble model : 0.96
Test Accuracy of ensemble model : 0.96

In [79]:
y_pred = ensemble.predict(X_test_scaled)
print('Classification Report : ')
print(classification_report(y_test, y_pred))
print('Confusion Matrix : ')
print(confusion_matrix(y_test, y_pred))

Classification Report :
              precision    recall  f1-score   support

           0       0.98      0.97      0.97        95
           1       0.93      0.96      0.95        45

    accuracy                           0.96       140
   macro avg       0.96      0.96      0.96       140
weighted avg       0.96      0.96      0.96       140

Confusion Matrix :
[[92  3]
 [ 2 43]]

In [81]:
# Advanced techniques used in ensemble learning
# -> use complex methods to merge predictions from many models
# -> aim for better predictive accuracy
# -> high predictive accuracy is crucial - financial forecasting, medical diagonsis

# Bagging (bootstrap aggregating)
# -> method -> creates multiple subsets from the original dataset - bootstrap samples
# -> each subset will train seperate model
# -> Final prediction -> model outputs using voting(classification) or averaging(regression)
# -> Random Forest -> uses bagging 
# -> multiple decision trees -> each tree working on differnt bootstrap
# -> combine the predictions

# Pima Indians -> diabetes dataset
url="https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
data = pd.read_csv(url, names=names)
data.head()

   preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [83]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   preg    768 non-null    int64
 1   plas    768 non-null    int64
 2   pres    768 non-null    int64
 3   skin    768 non-null    int64
 4   test    768 non-null    int64
 5   mass    768 non-null    float64
 6   pedi    768 non-null    float64
 7   age     768 non-null    int64
 8   class   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [85]:
data['class'].value_counts()

class
0    500
1    268
Name: count, dtype: int64

In [87]:
# get target and features
X = data.iloc[:,:-1]
y = data['class']
# split the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# scale MinMaXScaler
scaler = MinMaxScaler(feature_range=(0,1))
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [89]:
# Setup kfold cross validation splits as 10
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
# estimators as DTC -> num = 100
dtc = DecisionTreeClassifier()
num_trees = 100

In [93]:
from sklearn.ensemble import BaggingClassifier
bagging_model = BaggingClassifier(estimator=dtc, n_estimators=num_trees, random_state=42, oob_score=True)
# oob_score : method of measuring prediction error of random forest, bagging
# -> ensemble methods involve bootstrap(subsets) aggregating
results = cross_val_score(bagging_model, X_train_scaled, y_train, cv=kfold)
print(results)
mean_score = np.mean(results)
print("Mean Cross Validation Score : ", mean_score)

[0.72580645 0.70967742 0.77419355 0.75806452 0.73770492 0.80327869
 0.70491803 0.72131148 0.81967213 0.80327869]
Mean Cross Validation Score :  0.75579058699101

In [95]:
# fit the model and evaluate on testing set
bagging_model.fit(X_train_scaled, y_train)
# prediction and then evaluate
y_pred = bagging_model.predict(X_test_scaled)
print('Classification Report : ')
print(classification_report(y_test, y_pred))
print('Confusion Matrix : ')
print(confusion_matrix(y_test, y_pred))

Classification Report :
              precision    recall  f1-score   support

           0       0.81      0.79      0.80        99
           1       0.64      0.67      0.65        55

    accuracy                           0.75       154
   macro avg       0.73      0.73      0.73       154
weighted avg       0.75      0.75      0.75       154

Confusion Matrix :
[[78 21]
 [18 37]]

In [ ]:
# Boosting
# -> sequential ensemble technique
# -> model corrects its predecessor's errors
# -> AdaBoost, GBM (Gradient Boosting Machine), XGBoost

# AdaBoost :
# AdaBoost, an abbreviation for adaptive boosting, stands as one of the leading boosting algorithms with widespread adoption.
# It focuses on classification problems, aiming to transform a collection of weak classifiers into a single strong classifier. It increases the weights of misclassified instances, directing subsequent classifiers to pay more attention to challenging cases.
# The AdaBoost algorithm follows these steps:
# Initially, the algorithm assigns equal weights to all observations in the dataset.
# A model is constructed using a subset of the data.
# Predictions are made on the entire dataset using this model.
# The algorithm computes errors by comparing these predictions to the actual values.
# In the subsequent model creation, the algorithm assigns higher weights to incorrectly predicted data points.
# Weights are determined based on error values, where higher errors result in heavier observation weights.
# This iterative process continues until the error function stabilizes or the algorithm reaches the maximum limit of estimators.

In [97]:
# Load the dataset from the specified URL and assign column names to the DataFrame
data = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data', header=None)
data.columns = ['Sample code', 'Clump Thickness', 'Uniformity of Cell Size', 'Uniformity of Cell Shape',
                'Marginal Adhesion', 'Single Epithelial Cell Size', 'Bare Nuclei', 'Bland Chromatin',
                'Normal Nucleoli', 'Mitoses', 'Class']

# drop sample code col
data.drop(['Sample code'], axis=1, inplace=True)

# convert bare nuclei to interger type
import numpy as np
data = data.replace('?',np.nan)
data['Bare Nuclei'] = pd.to_numeric(data['Bare Nuclei']).fillna(0).astype('int64')

# Replace class values to binary ( 2 for benign, 4 for malignant)
data['Class'] = data['Class'].replace({2:0, 4:1})
data.head(10)

# Extract features X and target y
X = data.iloc[:,:-1] # all cols except last
y = data.iloc[:,-1] # last col as target

# Perform train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [107]:
# AdaBoost ALgorithm
from sklearn.pipeline import Pipeline
from sklearn.ensemble import AdaBoostClassifier

# define the cross validation
kfold = KFold(n_splits = 10, shuffle=True, random_state=42)
# Create a pipeline for AdaBoost classifier, n_estimators -> DTC 
adaboost_classifier = Pipeline([
    ('scaler', MinMaxScaler(feature_range=(0,1))),
    ('classifier',AdaBoostClassifier(n_estimators=70, random_state=42))
     ])

In [109]:
# fitting , prediction, evaluate
adaboost_classifier.fit(X_train, y_train)
y_pred = adaboost_classifier.predict(X_test)
print('Classification Report : ')
print(classification_report(y_test, y_pred))
print('Confusion Matrix : ')
print(confusion_matrix(y_test, y_pred))

Classification Report :
              precision    recall  f1-score   support

           0       0.97      0.98      0.97        95
           1       0.95      0.93      0.94        45

    accuracy                           0.96       140
   macro avg       0.96      0.96      0.96       140
weighted avg       0.96      0.96      0.96       140

Confusion Matrix :
[[93  2]
 [ 3 42]]

In [ ]:
# Gradient boosting
# refers to a class of ensemble machine learning algorithms that can be used for classification or regression 
# predictive modeling problems.
# Gradient boosting is also known as gradient tree boosting, stochastic gradient boosting (an extension), 
# and gradient boosting machines, or GBM for short.
# Ensembles are constructed from decision tree models. Trees are added one at a time to the ensemble
# and fit to correct the prediction errors made by prior models
# Gradient Boosting involves three main components:
# Loss Function: The choice of loss function depends on the type of problem being solved (e.g., regression, classification).
# The goal is to find a model that minimizes the loss function.
# Weak Learners: Gradient Boosting uses decision trees as the default weak learner. 
# These trees are usually of a fixed size and depth and are created one at a time.
# Additive Model: Instead of adjusting the weights of data points like AdaBoost,
# Gradient Boosting fits new models to the residual errors made by previous models. 
# Essentially, each new model is built on the errors of the whole ensemble so far.

In [113]:
from sklearn.ensemble import GradientBoostingClassifier

# pipeline
# fiiiting
# prediction
# evaluation
# GBDone

# define the cross validation
# kfold = KFold(n_splits = 10, shuffle=True, random_state=42)
# Create a pipeline for AdaBoost classifier, n_estimators -> DTC 
gbboost_classifier = Pipeline([
    ('scaler', MinMaxScaler(feature_range=(0,1))),
    ('classifier',GradientBoostingClassifier(n_estimators=70, random_state=42))
     ])

# fitting , prediction, evaluate
gbboost_classifier.fit(X_train, y_train)
y_pred = gbboost_classifier.predict(X_test)
print('Classification Report : ')
print(classification_report(y_test, y_pred))
print('Confusion Matrix : ')
print(confusion_matrix(y_test, y_pred))

Classification Report :
              precision    recall  f1-score   support

           0       0.96      0.98      0.97        95
           1       0.95      0.91      0.93        45

    accuracy                           0.96       140
   macro avg       0.96      0.95      0.95       140
weighted avg       0.96      0.96      0.96       140

Confusion Matrix :
[[93  2]
 [ 4 41]]

In [ ]:
# XGBoost
# XGBoost, or eXtreme Gradient Boosting, stands out as a premier machine learning framework,
# widely adopted for its proficiency in supervised learning tasks including classification, regression, and ranking.
# This advanced algorithm builds upon the principles of gradient boosting and is celebrated for its exceptional accuracy 
# and scalability in handling complex predictive modeling challenges.
# XGBoost offers many essential features that make it ideal for classification tasks. Some of the reasons include:
# High performance: As mentioned above, XGBoost is optimized for speed and efficiency, making it appropriate 
# for large datasets and real-time applications.
# Regularization methods: L1 (Lasso) and L2 (Ridge) regularisation terms are included in XGBoost 
# to avoid overfitting and increase generalization.
# Handle missing data: Moreover, XGBoost can handle missing data automatically, minimizing the need 
# for preprocessing and imputation.

# CatBoost
# Catboost is a variant of gradient boosting that can handle both categorical and numerical features.
# It does not require any feature encodings techniques like One-Hot Encoder or Label Encoder to convert 
# categorical features into numerical features.

In [ ]:
!pip install xgboost

In [ ]:
# brew install libomp - command prompt

In [125]:
# XGBoost
from xgboost import XGBClassifier

# try the code
xgbboost_classifier = Pipeline([
    ('scaler', MinMaxScaler(feature_range=(0,1))),
    ('classifier',XGBClassifier(n_estimators=50, random_state=42))
     ])

# fitting , prediction, evaluate
xgbboost_classifier.fit(X_train, y_train)
y_pred = xgbboost_classifier.predict(X_test)
print('Classification Report : ')
print(classification_report(y_test, y_pred))
print('Confusion Matrix : ')
print(confusion_matrix(y_test, y_pred))

Classification Report :
              precision    recall  f1-score   support

           0       0.97      0.98      0.97        95
           1       0.95      0.93      0.94        45

    accuracy                           0.96       140
   macro avg       0.96      0.96      0.96       140
weighted avg       0.96      0.96      0.96       140

Confusion Matrix :
[[93  2]
 [ 3 42]]

In [129]:
!pip install catboost

Collecting catboost
  Downloading catboost-1.2.8-cp312-cp312-win_amd64.whl.metadata (1.5 kB)
Collecting graphviz (from catboost)
  Downloading graphviz-0.21-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: matplotlib in c:\users\vandana\anaconda3\lib\site-packages (from catboost) (3.8.4)
Requirement already satisfied: numpy<3.0,>=1.16.0 in c:\users\vandana\anaconda3\lib\site-packages (from catboost) (1.26.4)
Requirement already satisfied: pandas>=0.24 in c:\users\vandana\anaconda3\lib\site-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in c:\users\vandana\anaconda3\lib\site-packages (from catboost) (1.14.1)
Requirement already satisfied: plotly in c:\users\vandana\anaconda3\lib\site-packages (from catboost) (5.22.0)
Requirement already satisfied: six in c:\users\vandana\anaconda3\lib\site-packages (from catboost) (1.16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\vandana\anaconda3\lib\site-packages (from pandas>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\vandana\anaconda3\lib\site-packages (from pandas>=0.24->catboost) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\vandana\anaconda3\lib\site-packages (from pandas>=0.24->catboost) (2023.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\vandana\anaconda3\lib\site-packages (from matplotlib->catboost) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\vandana\anaconda3\lib\site-packages (from matplotlib->catboost) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\vandana\anaconda3\lib\site-packages (from matplotlib->catboost) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\vandana\anaconda3\lib\site-packages (from matplotlib->catboost) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\vandana\anaconda3\lib\site-packages (from matplotlib->catboost) (23.2)
Requirement already satisfied: pillow>=8 in c:\users\vandana\anaconda3\lib\site-packages (from matplotlib->catboost) (10.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\vandana\anaconda3\lib\site-packages (from matplotlib->catboost) (3.0.9)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\vandana\anaconda3\lib\site-packages (from plotly->catboost) (8.2.2)
Downloading catboost-1.2.8-cp312-cp312-win_amd64.whl (102.4 MB)
   ---------------------------------------- 0.0/102.4 MB ? eta -:--:--
   ---------------------------------------- 1.0/102.4 MB 4.6 MB/s eta 0:00:23
    --------------------------------------- 1.8/102.4 MB 4.4 MB/s eta 0:00:23
   - -------------------------------------- 2.6/102.4 MB 4.2 MB/s eta 0:00:24
   - -------------------------------------- 3.4/102.4 MB 4.2 MB/s eta 0:00:24
   - -------------------------------------- 4.2/102.4 MB 4.1 MB/s eta 0:00:25
   -- ------------------------------------- 5.2/102.4 MB 4.0 MB/s eta 0:00:25
   -- ------------------------------------- 6.0/102.4 MB 4.0 MB/s eta 0:00:25
   -- ------------------------------------- 6.8/102.4 MB 4.0 MB/s eta 0:00:25
   -- ------------------------------------- 7.3/102.4 MB 3.8 MB/s eta 0:00:25
   --- ------------------------------------ 8.4/102.4 MB 3.8 MB/s eta 0:00:25
   --- ------------------------------------ 9.4/102.4 MB 3.9 MB/s eta 0:00:24
   --- ------------------------------------ 10.2/102.4 MB 3.9 MB/s eta 0:00:24
   ---- ----------------------------------- 11.0/102.4 MB 3.9 MB/s eta 0:00:24
   ---- ----------------------------------- 11.5/102.4 MB 3.9 MB/s eta 0:00:24
   ---- ----------------------------------- 12.3/102.4 MB 3.8 MB/s eta 0:00:24
   ---- ----------------------------------- 12.6/102.4 MB 3.7 MB/s eta 0:00:25
   ----- ---------------------------------- 13.4/102.4 MB 3.6 MB/s eta 0:00:25
   ----- ---------------------------------- 13.9/102.4 MB 3.5 MB/s eta 0:00:25
   ----- ---------------------------------- 14.2/102.4 MB 3.5 MB/s eta 0:00:26
   ----- ---------------------------------- 14.4/102.4 MB 3.4 MB/s eta 0:00:26
   ----- ---------------------------------- 14.7/102.4 MB 3.3 MB/s eta 0:00:27
   ----- ---------------------------------- 15.2/102.4 MB 3.2 MB/s eta 0:00:28
   ------ --------------------------------- 15.5/102.4 MB 3.1 MB/s eta 0:00:28
   ------ --------------------------------- 15.7/102.4 MB 3.1 MB/s eta 0:00:28
   ------ --------------------------------- 16.3/102.4 MB 3.0 MB/s eta 0:00:29
   ------ --------------------------------- 16.8/102.4 MB 3.0 MB/s eta 0:00:29
   ------ --------------------------------- 17.3/102.4 MB 2.9 MB/s eta 0:00:29
   ------ --------------------------------- 17.6/102.4 MB 2.9 MB/s eta 0:00:29
   ------- -------------------------------- 18.6/102.4 MB 3.0 MB/s eta 0:00:29
   ------- -------------------------------- 19.1/102.4 MB 3.0 MB/s eta 0:00:29
   ------- -------------------------------- 19.9/102.4 MB 3.0 MB/s eta 0:00:28
   ------- -------------------------------- 20.4/102.4 MB 3.0 MB/s eta 0:00:28
   -------- ------------------------------- 21.0/102.4 MB 3.0 MB/s eta 0:00:28
   -------- ------------------------------- 21.5/102.4 MB 2.9 MB/s eta 0:00:28
   -------- ------------------------------- 21.8/102.4 MB 2.9 MB/s eta 0:00:28
   -------- ------------------------------- 22.0/102.4 MB 2.8 MB/s eta 0:00:29
   -------- ------------------------------- 22.5/102.4 MB 2.8 MB/s eta 0:00:29
   -------- ------------------------------- 22.8/102.4 MB 2.8 MB/s eta 0:00:29
   --------- ------------------------------ 23.1/102.4 MB 2.8 MB/s eta 0:00:29
   --------- ------------------------------ 23.6/102.4 MB 2.7 MB/s eta 0:00:29
   --------- ------------------------------ 24.4/102.4 MB 2.8 MB/s eta 0:00:29
   --------- ------------------------------ 25.2/102.4 MB 2.8 MB/s eta 0:00:28
   ---------- ----------------------------- 25.7/102.4 MB 2.8 MB/s eta 0:00:28
   ---------- ----------------------------- 26.2/102.4 MB 2.8 MB/s eta 0:00:28
   ---------- ----------------------------- 26.5/102.4 MB 2.8 MB/s eta 0:00:28
   ---------- ----------------------------- 26.5/102.4 MB 2.8 MB/s eta 0:00:28
   ---------- ----------------------------- 26.7/102.4 MB 2.7 MB/s eta 0:00:29
   ---------- ----------------------------- 27.0/102.4 MB 2.6 MB/s eta 0:00:29
   ---------- ----------------------------- 27.0/102.4 MB 2.6 MB/s eta 0:00:29
   ---------- ----------------------------- 27.3/102.4 MB 2.6 MB/s eta 0:00:30
   ---------- ----------------------------- 27.8/102.4 MB 2.5 MB/s eta 0:00:30
   ----------- ---------------------------- 28.3/102.4 MB 2.5 MB/s eta 0:00:30
   ----------- ---------------------------- 28.8/102.4 MB 2.5 MB/s eta 0:00:30
   ----------- ---------------------------- 29.4/102.4 MB 2.5 MB/s eta 0:00:29
   ----------- ---------------------------- 29.6/102.4 MB 2.5 MB/s eta 0:00:30
   ----------- ---------------------------- 29.9/102.4 MB 2.5 MB/s eta 0:00:29
   ----------- ---------------------------- 30.4/102.4 MB 2.5 MB/s eta 0:00:29
   ------------ --------------------------- 31.2/102.4 MB 2.5 MB/s eta 0:00:29
   ------------ --------------------------- 31.7/102.4 MB 2.5 MB/s eta 0:00:29
   ------------ --------------------------- 32.2/102.4 MB 2.5 MB/s eta 0:00:28
   ------------ --------------------------- 32.8/102.4 MB 2.5 MB/s eta 0:00:28
   ------------ --------------------------- 33.0/102.4 MB 2.5 MB/s eta 0:00:29
   ------------ --------------------------- 33.0/102.4 MB 2.5 MB/s eta 0:00:29
   ------------- -------------------------- 33.6/102.4 MB 2.4 MB/s eta 0:00:29
   ------------- -------------------------- 34.1/102.4 MB 2.4 MB/s eta 0:00:29
   ------------- -------------------------- 34.6/102.4 MB 2.4 MB/s eta 0:00:28
   ------------- -------------------------- 35.1/102.4 MB 2.4 MB/s eta 0:00:28
   ------------- -------------------------- 35.4/102.4 MB 2.4 MB/s eta 0:00:28
   ------------- -------------------------- 35.7/102.4 MB 2.4 MB/s eta 0:00:28
   -------------- ------------------------- 36.2/102.4 MB 2.4 MB/s eta 0:00:28
   -------------- ------------------------- 36.4/102.4 MB 2.4 MB/s eta 0:00:28
   -------------- ------------------------- 36.7/102.4 MB 2.4 MB/s eta 0:00:28
   -------------- ------------------------- 36.7/102.4 MB 2.4 MB/s eta 0:00:28
   -------------- ------------------------- 37.2/102.4 MB 2.3 MB/s eta 0:00:28
   -------------- ------------------------- 37.7/102.4 MB 2.3 MB/s eta 0:00:28
   -------------- ------------------------- 38.0/102.4 MB 2.3 MB/s eta 0:00:28
   --------------- ------------------------ 38.5/102.4 MB 2.3 MB/s eta 0:00:28
   --------------- ------------------------ 39.1/102.4 MB 2.3 MB/s eta 0:00:28
   --------------- ------------------------ 39.3/102.4 MB 2.3 MB/s eta 0:00:28
   --------------- ------------------------ 39.6/102.4 MB 2.3 MB/s eta 0:00:28
   --------------- ------------------------ 40.1/102.4 MB 2.3 MB/s eta 0:00:28
   --------------- ------------------------ 40.6/102.4 MB 2.3 MB/s eta 0:00:27
   --------------- ------------------------ 40.9/102.4 MB 2.3 MB/s eta 0:00:27
   ---------------- ----------------------- 41.4/102.4 MB 2.3 MB/s eta 0:00:27
   ---------------- ----------------------- 41.9/102.4 MB 2.3 MB/s eta 0:00:27
   ---------------- ----------------------- 42.7/102.4 MB 2.3 MB/s eta 0:00:26
   ---------------- ----------------------- 43.5/102.4 MB 2.3 MB/s eta 0:00:26
   ----------------- ---------------------- 44.0/102.4 MB 2.3 MB/s eta 0:00:26
   ----------------- ---------------------- 44.6/102.4 MB 2.3 MB/s eta 0:00:25
   ----------------- ---------------------- 45.1/102.4 MB 2.3 MB/s eta 0:00:25
   ----------------- ---------------------- 45.4/102.4 MB 2.3 MB/s eta 0:00:25
   ----------------- ---------------------- 45.6/102.4 MB 2.3 MB/s eta 0:00:25
   ----------------- ---------------------- 45.9/102.4 MB 2.3 MB/s eta 0:00:25
   ------------------ --------------------- 46.4/102.4 MB 2.3 MB/s eta 0:00:25
   ------------------ --------------------- 47.2/102.4 MB 2.3 MB/s eta 0:00:24
   ------------------ --------------------- 47.7/102.4 MB 2.3 MB/s eta 0:00:24
   ------------------ --------------------- 48.2/102.4 MB 2.3 MB/s eta 0:00:24
   ------------------- -------------------- 49.0/102.4 MB 2.3 MB/s eta 0:00:24
   ------------------- -------------------- 49.8/102.4 MB 2.3 MB/s eta 0:00:23
   ------------------- -------------------- 50.6/102.4 MB 2.4 MB/s eta 0:00:23
   -------------------- ------------------- 51.4/102.4 MB 2.4 MB/s eta 0:00:22
   -------------------- ------------------- 52.4/102.4 MB 2.4 MB/s eta 0:00:21
   -------------------- ------------------- 53.2/102.4 MB 2.4 MB/s eta 0:00:21
   --------------------- ------------------ 54.3/102.4 MB 2.4 MB/s eta 0:00:20
   --------------------- ------------------ 55.1/102.4 MB 2.4 MB/s eta 0:00:20
   --------------------- ------------------ 55.8/102.4 MB 2.4 MB/s eta 0:00:20
   ---------------------- ----------------- 56.4/102.4 MB 2.4 MB/s eta 0:00:19
   ---------------------- ----------------- 56.9/102.4 MB 2.4 MB/s eta 0:00:19
   ---------------------- ----------------- 57.7/102.4 MB 2.5 MB/s eta 0:00:19
   ---------------------- ----------------- 58.5/102.4 MB 2.5 MB/s eta 0:00:18
   ----------------------- ---------------- 59.0/102.4 MB 2.5 MB/s eta 0:00:18
   ----------------------- ---------------- 59.8/102.4 MB 2.5 MB/s eta 0:00:18
   ----------------------- ---------------- 60.6/102.4 MB 2.5 MB/s eta 0:00:17
   ----------------------- ---------------- 61.1/102.4 MB 2.5 MB/s eta 0:00:17
   ------------------------ --------------- 61.6/102.4 MB 2.5 MB/s eta 0:00:17
   ------------------------ --------------- 62.4/102.4 MB 2.5 MB/s eta 0:00:17
   ------------------------ --------------- 62.9/102.4 MB 2.5 MB/s eta 0:00:16
   ------------------------ --------------- 63.4/102.4 MB 2.5 MB/s eta 0:00:16
   ------------------------ --------------- 64.0/102.4 MB 2.5 MB/s eta 0:00:16
   ------------------------- -------------- 64.5/102.4 MB 2.5 MB/s eta 0:00:16
   ------------------------- -------------- 64.7/102.4 MB 2.5 MB/s eta 0:00:16
   ------------------------- -------------- 65.3/102.4 MB 2.5 MB/s eta 0:00:15
   ------------------------- -------------- 65.8/102.4 MB 2.5 MB/s eta 0:00:15
   -------------------------- ------------- 66.6/102.4 MB 2.5 MB/s eta 0:00:15
   -------------------------- ------------- 67.6/102.4 MB 2.5 MB/s eta 0:00:14
   -------------------------- ------------- 68.7/102.4 MB 2.5 MB/s eta 0:00:14
   --------------------------- ------------ 69.2/102.4 MB 2.5 MB/s eta 0:00:14
   --------------------------- ------------ 69.7/102.4 MB 2.5 MB/s eta 0:00:13
   --------------------------- ------------ 70.5/102.4 MB 2.5 MB/s eta 0:00:13
   --------------------------- ------------ 71.0/102.4 MB 2.5 MB/s eta 0:00:13
   --------------------------- ------------ 71.3/102.4 MB 2.5 MB/s eta 0:00:13
   ---------------------------- ----------- 71.8/102.4 MB 2.5 MB/s eta 0:00:13
   ---------------------------- ----------- 72.6/102.4 MB 2.5 MB/s eta 0:00:12
   ---------------------------- ----------- 73.4/102.4 MB 2.5 MB/s eta 0:00:12
   ---------------------------- ----------- 73.9/102.4 MB 2.5 MB/s eta 0:00:12
   ----------------------------- ---------- 74.4/102.4 MB 2.5 MB/s eta 0:00:11
   ----------------------------- ---------- 75.0/102.4 MB 2.5 MB/s eta 0:00:11
   ----------------------------- ---------- 75.5/102.4 MB 2.5 MB/s eta 0:00:11
   ----------------------------- ---------- 76.0/102.4 MB 2.5 MB/s eta 0:00:11
   ----------------------------- ---------- 76.8/102.4 MB 2.5 MB/s eta 0:00:11
   ------------------------------ --------- 77.6/102.4 MB 2.5 MB/s eta 0:00:10
   ------------------------------ --------- 78.9/102.4 MB 2.5 MB/s eta 0:00:10
   ------------------------------- -------- 79.7/102.4 MB 2.6 MB/s eta 0:00:09
   ------------------------------- -------- 80.5/102.4 MB 2.6 MB/s eta 0:00:09
   ------------------------------- -------- 81.5/102.4 MB 2.6 MB/s eta 0:00:09
   -------------------------------- ------- 82.3/102.4 MB 2.6 MB/s eta 0:00:08
   -------------------------------- ------- 83.1/102.4 MB 2.5 MB/s eta 0:00:08
   -------------------------------- ------- 83.9/102.4 MB 2.6 MB/s eta 0:00:08
   -------------------------------- ------- 84.4/102.4 MB 2.5 MB/s eta 0:00:08
   --------------------------------- ------ 84.9/102.4 MB 2.5 MB/s eta 0:00:07
   --------------------------------- ------ 85.7/102.4 MB 2.5 MB/s eta 0:00:07
   --------------------------------- ------ 86.5/102.4 MB 2.5 MB/s eta 0:00:07
   ---------------------------------- ----- 87.6/102.4 MB 2.5 MB/s eta 0:00:06
   ---------------------------------- ----- 88.3/102.4 MB 2.5 MB/s eta 0:00:06
   ---------------------------------- ----- 89.4/102.4 MB 2.6 MB/s eta 0:00:06
   ----------------------------------- ---- 90.2/102.4 MB 2.6 MB/s eta 0:00:05
   ----------------------------------- ---- 90.7/102.4 MB 2.6 MB/s eta 0:00:05
   ----------------------------------- ---- 91.8/102.4 MB 2.6 MB/s eta 0:00:05
   ------------------------------------ --- 92.5/102.4 MB 2.6 MB/s eta 0:00:04
   ------------------------------------ --- 93.3/102.4 MB 2.6 MB/s eta 0:00:04
   ------------------------------------ --- 94.4/102.4 MB 2.7 MB/s eta 0:00:04
   ------------------------------------- -- 95.2/102.4 MB 2.7 MB/s eta 0:00:03
   ------------------------------------- -- 95.9/102.4 MB 2.7 MB/s eta 0:00:03
   ------------------------------------- -- 96.7/102.4 MB 2.7 MB/s eta 0:00:03
   -------------------------------------- - 97.5/102.4 MB 2.7 MB/s eta 0:00:02
   -------------------------------------- - 98.0/102.4 MB 2.7 MB/s eta 0:00:02
   -------------------------------------- - 98.6/102.4 MB 2.7 MB/s eta 0:00:02
   -------------------------------------- - 99.1/102.4 MB 2.7 MB/s eta 0:00:02
   -------------------------------------- - 99.6/102.4 MB 2.7 MB/s eta 0:00:02
   ---------------------------------------  100.1/102.4 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------  101.2/102.4 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------  102.2/102.4 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------  102.2/102.4 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------- 102.4/102.4 MB 2.7 MB/s eta 0:00:00
Downloading graphviz-0.21-py3-none-any.whl (47 kB)
Installing collected packages: graphviz, catboost

   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   ---------------------------------------- 2/2 [catboost]

Successfully installed catboost-1.2.8 graphviz-0.21

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [135]:
# CatBoost
from catboost import CatBoostClassifier

catboost_classifier = Pipeline([
    ('scaler', MinMaxScaler(feature_range=(0,1))),
    ('classifier',CatBoostClassifier(n_estimators=70, random_state=42))
     ])
# fitting , prediction, evaluate
catboost_classifier.fit(X_train, y_train)
y_pred = catboost_classifier.predict(X_test)
print('Classification Report : ')
print(classification_report(y_test, y_pred))
print('Confusion Matrix : ')
print(confusion_matrix(y_test, y_pred))

Learning rate set to 0.092071
0:	learn: 0.6292550	total: 446us	remaining: 30.8ms
1:	learn: 0.5752903	total: 804us	remaining: 27.4ms
2:	learn: 0.5268972	total: 1.42ms	remaining: 31.8ms
3:	learn: 0.4856345	total: 1.79ms	remaining: 29.5ms
4:	learn: 0.4467567	total: 2ms	remaining: 26.1ms
5:	learn: 0.4167929	total: 2.32ms	remaining: 24.7ms
6:	learn: 0.3876566	total: 2.63ms	remaining: 23.7ms
7:	learn: 0.3614817	total: 2.94ms	remaining: 22.8ms
8:	learn: 0.3391978	total: 3.25ms	remaining: 22ms
9:	learn: 0.3181865	total: 3.61ms	remaining: 21.6ms
10:	learn: 0.2993729	total: 3.94ms	remaining: 21.1ms
11:	learn: 0.2839795	total: 4.34ms	remaining: 21ms
12:	learn: 0.2677567	total: 4.68ms	remaining: 20.5ms
13:	learn: 0.2544188	total: 5ms	remaining: 20ms
14:	learn: 0.2417225	total: 5.33ms	remaining: 19.6ms
15:	learn: 0.2289638	total: 5.64ms	remaining: 19ms
16:	learn: 0.2177124	total: 5.96ms	remaining: 18.6ms
17:	learn: 0.2068059	total: 6.28ms	remaining: 18.1ms
18:	learn: 0.1962926	total: 6.46ms	remaining: 17.4ms
19:	learn: 0.1875336	total: 6.77ms	remaining: 16.9ms
20:	learn: 0.1803760	total: 7.08ms	remaining: 16.5ms
21:	learn: 0.1738482	total: 7.39ms	remaining: 16.1ms
22:	learn: 0.1675285	total: 7.92ms	remaining: 16.2ms
23:	learn: 0.1609690	total: 8.25ms	remaining: 15.8ms
24:	learn: 0.1559076	total: 13.1ms	remaining: 23.7ms
25:	learn: 0.1504680	total: 13.5ms	remaining: 22.8ms
26:	learn: 0.1454877	total: 13.8ms	remaining: 22ms
27:	learn: 0.1410284	total: 14.3ms	remaining: 21.5ms
28:	learn: 0.1372186	total: 14.7ms	remaining: 20.7ms
29:	learn: 0.1331992	total: 15.5ms	remaining: 20.7ms
30:	learn: 0.1297227	total: 15.8ms	remaining: 19.9ms
31:	learn: 0.1262861	total: 16.5ms	remaining: 19.6ms
32:	learn: 0.1234064	total: 17.1ms	remaining: 19.1ms
33:	learn: 0.1206972	total: 17.5ms	remaining: 18.5ms
34:	learn: 0.1176857	total: 17.9ms	remaining: 17.9ms
35:	learn: 0.1151069	total: 18.2ms	remaining: 17.2ms
36:	learn: 0.1124876	total: 18.6ms	remaining: 16.6ms
37:	learn: 0.1097425	total: 18.9ms	remaining: 15.9ms
38:	learn: 0.1073802	total: 19.2ms	remaining: 15.3ms
39:	learn: 0.1047992	total: 19.5ms	remaining: 14.6ms
40:	learn: 0.1031256	total: 19.8ms	remaining: 14ms
41:	learn: 0.1012016	total: 20.1ms	remaining: 13.4ms
42:	learn: 0.0993953	total: 20.4ms	remaining: 12.8ms
43:	learn: 0.0969873	total: 20.8ms	remaining: 12.3ms
44:	learn: 0.0953669	total: 21.1ms	remaining: 11.7ms
45:	learn: 0.0937442	total: 21.4ms	remaining: 11.2ms
46:	learn: 0.0923252	total: 21.7ms	remaining: 10.6ms
47:	learn: 0.0905616	total: 22ms	remaining: 10.1ms
48:	learn: 0.0888705	total: 22.3ms	remaining: 9.57ms
49:	learn: 0.0876342	total: 22.6ms	remaining: 9.05ms
50:	learn: 0.0860588	total: 22.9ms	remaining: 8.54ms
51:	learn: 0.0849634	total: 23.3ms	remaining: 8.05ms
52:	learn: 0.0835609	total: 25.6ms	remaining: 8.2ms
53:	learn: 0.0824424	total: 25.9ms	remaining: 7.69ms
54:	learn: 0.0814992	total: 26.3ms	remaining: 7.17ms
55:	learn: 0.0804589	total: 26.6ms	remaining: 6.66ms
56:	learn: 0.0796478	total: 27ms	remaining: 6.15ms
57:	learn: 0.0786853	total: 27.3ms	remaining: 5.65ms
58:	learn: 0.0778406	total: 27.6ms	remaining: 5.14ms
59:	learn: 0.0771483	total: 27.9ms	remaining: 4.65ms
60:	learn: 0.0762938	total: 28.2ms	remaining: 4.16ms
61:	learn: 0.0752372	total: 28.5ms	remaining: 3.68ms
62:	learn: 0.0742793	total: 28.8ms	remaining: 3.2ms
63:	learn: 0.0732669	total: 29.1ms	remaining: 2.73ms
64:	learn: 0.0723182	total: 29.5ms	remaining: 2.27ms
65:	learn: 0.0713354	total: 29.8ms	remaining: 1.8ms
66:	learn: 0.0704647	total: 30.1ms	remaining: 1.35ms
67:	learn: 0.0701188	total: 30.5ms	remaining: 895us
68:	learn: 0.0692147	total: 30.8ms	remaining: 445us
69:	learn: 0.0685092	total: 31.1ms	remaining: 0us
Classification Report :
              precision    recall  f1-score   support

           0       0.98      0.98      0.98        95
           1       0.96      0.96      0.96        45

    accuracy                           0.97       140
   macro avg       0.97      0.97      0.97       140
weighted avg       0.97      0.97      0.97       140

Confusion Matrix :
[[93  2]
 [ 2 43]]

In [ ]:
# Stacking combines multiple classification or regression models via a meta model which could be a meta-classifier 
# or a meta-regressor. After training the base models on the complete dataset, 
# the meta-model trains on the base models' outputs as features, to give final prediction.

# This technique leverages the strengths of each base model and can achieve higher accuracy.

# In stacking, as opposed to bagging, a variety of models (not solely decision trees) are employed, 
# all of which are trained on the same full dataset rather than on subsets.
# Unlike boosting, in stacking, a single model is used to learn how to best combine the 
# predictions from the contributing models (e.g. instead of a sequence of models that correct the predictions of prior models).

# Stacking aims to leverage the advantages of different base models by inputting their predictions into a meta-model.
# The structure of a stacking model consists of multiple base models, also known as level-0 models, 
#alongside a meta-model that integrates their predictions, known as the level-1 model.

# Level-0 Models (Base Models): These models are trained on the full training dataset, 
# and their individual predictions are aggregated.
# Level-1 Model (Meta-Model): This model is designed to optimally combine the predictions
# of multiple base models to generate the final prediction.

In [139]:
# python pakcage vecstack
!pip install vecstack

Collecting vecstack
  Downloading vecstack-0.5.2-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: numpy in c:\users\vandana\anaconda3\lib\site-packages (from vecstack) (1.26.4)
Requirement already satisfied: scipy in c:\users\vandana\anaconda3\lib\site-packages (from vecstack) (1.14.1)
Requirement already satisfied: scikit-learn>=1.6.0 in c:\users\vandana\anaconda3\lib\site-packages (from vecstack) (1.7.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\vandana\anaconda3\lib\site-packages (from scikit-learn>=1.6.0->vecstack) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\vandana\anaconda3\lib\site-packages (from scikit-learn>=1.6.0->vecstack) (3.6.0)
Downloading vecstack-0.5.2-py3-none-any.whl (22 kB)
Installing collected packages: vecstack
Successfully installed vecstack-0.5.2

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [141]:
from vecstack import stacking

In [143]:
# Define the URL of the dataset
link = 'https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data'

# Define column names for the dataset
names = ['Class', 'Alcohol', 'Malic acid', 'Ash',
         'Alkalinity of ash', 'Magnesium', 'Total phenols',
         'Flavanoids', 'Nonflavanoid phenols', 'Proanthocyanins',
         'Color intensity', 'Hue', 'OD280/OD315 of diluted wines',
         'Proline']

In [145]:
# read the dataset into DataFrame
import pandas as pd
df = pd.read_csv(link,header=None,names=names)
df.head()

,Class,Alcohol,Malic acid,Ash,Alkalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [153]:
df['Class'].value_counts()

Class
2    71
1    59
3    48
Name: count, dtype: int64

In [151]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
X = df.drop('Class',axis=1)
y = df['Class']
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# Define base Models
models = [KNeighborsClassifier(n_neighbors=5),
          RandomForestClassifier(n_estimators=100,random_state=42),
          XGBClassifier(eval_metric='mlogloss',use_label_encoder=False)]
# define metamodel
meta_model = LogisticRegression(max_iter=1000)
# perform stacking
S_train, S_test = stacking(models, X_train, y_train, X_test,regression=False, metric=accuracy_score,
                        n_folds=5, shuffle=True, random_state=42)
# Train meta model with new set
meta_model.fit(S_train, y_train)
y_pred = meta_model.predict(S_test)
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy : {accuracy:.2f}')

ValueError: Invalid classes inferred from unique values of `y`.  Expected: [0 1 2], got [1 2 3]